services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Sensible defaults; .env can override
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - DB_PATH=${DB_PATH:-/data/app.db}
    volumes:
      - dbdata:/data

volumes:
  dbdata:
